# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 16:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170708_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='liked_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='liked_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='shared_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shared_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='liked_posts',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='liked_post', to='main.Post'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='posts',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Post'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shared_posts',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shared_posts', to='main.Post'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscribed_pages',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
    ]
