# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 16:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170708_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='liked_posts',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='shared_posts',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscribed_pages',
        ),
        migrations.AlterField(
            model_name='comment',
            name='liked_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='liked_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='shared_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='shared_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
