# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170708_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=15)),
                ('body', models.TextField(max_length=500)),
                ('time_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
