# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default='', max_length=500),
        ),
    ]
