# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liked_by',
        ),
        migrations.RemoveField(
            model_name='post',
            name='shared_by',
        ),
        migrations.AddField(
            model_name='profile',
            name='liked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='main.Post'),
        ),
        migrations.AddField(
            model_name='profile',
            name='shared',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_by', to='main.Post'),
        ),
    ]
