# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comments_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_page_for_anonymous_user',
            field=models.BooleanField(default=True),
        ),
    ]
